wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.7
    cli_version: 0.18.7
    framework: huggingface
    huggingface_version: 4.46.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1733421786
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      3:
      - 4
      - 13
      - 23
      - 42
      - 55
      4: 3.12.7
      5: 0.18.7
      6: 4.46.1
      8:
      - 5
      13: linux-x86_64
